---
- name: '[dependencies] Install sudo package'
  package:
    name:
      - sudo
      - locales
    state: present
  become: yes
  tags:
    - bootstrap_core
    - bootstrap_core_dependencies
...
